version: "3.8"

services: 

  mini_video_react_app_image:
    build: frontend
    container_name: mini_video_react_app_container
    ports: 
      - "3000:3000"
    networks: 
      - mini_video_app_network

  mini_video_app_server_image:
    build: backend
    container_name: mini_video_server_container
    ports: 
      - "8080:8080"
    depends_on: 
      mini_video_app_db:
        condition: service_healthy
    networks: 
      - mini_video_app_network
    environment: 
      DB_CONNECTION_STRING: postgres://postgres:docker@mini_video_app_db_container:5432/mini_video_app_db
      #use this DB_CONNECTION_STRING(set up in the knex file so that the server_image image and the server_db image can communicate?)
      
  mini_video_app_db:
    image: postgres:latest
    container_name: mini_video_app_db_container
    ports:
      - "5432:5432"
    healthcheck: 
      test: pg_isready -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mini_video_app_db
    networks: 
      - mini_video_app_network


# docker-compose up appears to create its own network

networks:
  mini_video_app_network:
    driver: bridge


